apiVersion: v1
kind: Service
metadata:
  name: brew-and-co-backend
  namespace: brew-and-co
  labels:
    app: brew-and-co-backend
spec:
  type: ClusterIP
  selector:
    app: brew-and-co-backend
  ports:
    - name: http
      port: 3000
      targetPort: http
